version: 0.2

env:
  shell: bash
phases:
  install: 
    runtime-versions:
      php: 7.4
  pre_build:
    commands:
    - echo Logging in to Amazon ECR....
    - aws --version
    - eval $(aws ecr get-login --region eu-west-1 --no-include-email | sed 's|https://||')
    - REPOSITORY_URI_PHP=046756490856.dkr.ecr.eu-west-2.amazonaws.com/budgeter-cp-php-fpm
    - IMAGE_TAG_PHP=latest
    - REPOSITORY_URI_NGINX=046756490856.dkr.ecr.eu-west-2.amazonaws.com/budgeter-cp-nginx
    - IMAGE_TAG_PHP=latest
    - cp .env.cp .env
  build:
    commands:
    - echo Build started on `date`
    - echo Building the NGINX Docker image...
    - docker build --target laravelapp_nginx -t $REPOSITORY_URI_NGINX:latest .
    - docker tag $REPOSITORY_URI_NGINX:latest $REPOSITORY_URI_NGINX:$IMAGE_TAG_PHP
    - echo Building the PHP Docker image...
    - docker build --target laravelapp_php -t $REPOSITORY_URI_PHP:latest .
    - docker tag $REPOSITORY_URI_PHP:latest $REPOSITORY_URI_PHP:$IMAGE_TAG_PHP
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - docker push $REPOSITORY_URI_NGINX:$IMAGE_TAG_NGINX
      - docker push $REPOSITORY_URI_PHP:$IMAGE_TAG_PHP 